# 配置文件请严格遵循yaml语法格式，yaml学习地址:
#  https://ansible-tran.readthedocs.io/en/latest/docs/YAMLSyntax.html
#  http://einverne.github.io/post/2015/08/yaml.html

alarm_timed: '06:00'
girlfriend_infos:
  -
    #女友微信昵称
    wechat_name: 'hc'
    #女友所在桂林
    city_name: '东莞'
    # 从那天开始勾搭的
    start_date: '2008-09-01'
    # 短句的最后留言
    sweet_words: '来自最爱你的wl_lw。'

  #如果有你多个人需要发送，则参照这个样式，复制即可
  #-
  #  wechat_name: '陈老师'
  #  city_name: '朝阳区'
  #  start_date: '2018-11-11'
  #  sweet_words: '来自你俊美的老公。'



